### ISSUE TITLE
History's date is not ISO/RFC2822 compliant. 

### ISSUE THREAD

**Issue by pironic** [WritheM/IntelliMerge#13]
**Describe the bug**
```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: Thu May 07 2020 13:45:24 GMT-0600 (Mountain Daylight Time), _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js:1:3368)
    at Ot (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js:1:21539)
    at Tt (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js:1:22250)
    at bt (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js:1:22332)
    at c (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js:1:209)
    at HTMLTableCellElement.<anonymous> (https://writhem.net/intellimerge/lib/script.min.js:1:71190)
    at Function.each (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js:2:2777)
    at k.fn.init.each (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js:2:1419)
    at prettyDate (https://writhem.net/intellimerge/lib/script.min.js:1:71165)
    at buildMasterPlaylistHistoryTable (https://writhem.net/intellimerge/lib/script.min.js:1:63001)
```

**To Reproduce**
Settings window click Show History > view browser console.
```<td class="moment" title="Thu May 07 2020 13:45:24 GMT-0600 (Mountain Daylight Time)">last Thu</td>```

**Expected behavior**
```<td class="moment" title="Thu, 07 May 2020 19:45:24 GMT">last Thu</td>```

**Comment by pironic** [comment]
fixed in next release
